### ISSUE TITLE
[Bug] Sweet Alert Not works

### ISSUE THREAD

**Issue by i-chirkov** [creativetimofficial/ct-nuxt-argon-dashboard-pro#2]
### Version
1.0
### Reproduction link
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/plugins/sweetalert.html
### Operating System
MacOS
### Device
Macbook
### Browser & Version
Opera 62.0.3331.119
### Steps to reproduce
Just try to click btn
### What is expected?
Everything works
### What is actually happening?
Error in console

---

**Comment by headofthetable** [comment]
The sweet alerts work here:
https://demos.creative-tim.com/nuxt-argon-dashboard-pro/components/notifications

The problem occurs in the docs because the Sweet Alert in the docs is using the old Sweet Alert API. It is using `swal` (which is what it used to be) and needs to be changed to `swal.fire` as it is in the actual dashboard itself

**Comment by i-chirkov** [comment]
Will you fix it in docs?

**Comment by cristijora** [comment]
This issue was fixed in version 1.2.0 along with other fixes & improvements.
For more details check the detailed [changelog here](https://demos.creative-tim.com/nuxt-argon-dashboard-pro/documentation/changelog.html)
